version: '3.3'
services:
  email:
    image: maildev/maildev
    user: ${RUNAS}
    ports:
      - "1080:1080"
  web:
    image: node:20
    user: ${RUNAS}
    depends_on:
      - email
    ports:
      - "3000:3000"
    volumes:
      - ../:/tmp/src
    environment:
      SMTP_HOST: email
      SMTP_PORT: 1025
    working_dir: /tmp/src
    command: bash -c 'sleep 5; npm start'
