#!/bin/bash

# This script runs the server and required components.

SCRIPT_DIR=$(dirname "$0")
SCRIPT_DIR_PARENT=$(cd "$SCRIPT_DIR" && cd ../ && pwd)

RUNAS="$(id -u):$(id -g)" docker-compose -f "$SCRIPT_DIR_PARENT/docker/docker-run-compose.yml" up --detach
